[package]
name = "stlwrap"
version = "0.1.0"
authors = ["James Stanley <james@incoherency.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"

[dependencies.stl]
path = "./rust-stl/"
